apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: spring-micrometer-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: spring-micrometer-prometheus
            image: avpatel257/spring-micrometer-prometheus:latest
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
